# BUILDER IMAGE
FROM openjdk:8-alpine as Builder
COPY gradlew .
COPY build.gradle .
COPY settings.gradle .
COPY .env .

COPY gradle gradle
COPY src src

RUN echo "SOURCE COPY COMPLETE"

RUN chmod +x ./gradlew

RUN ./gradlew clean
RUN ./gradlew build

RUN echo "BUILD COMPLETE"

# BASE IMAGE
FROM openjdk:8-alpine
COPY --from=Builder build/libs/*.jar app.jar

RUN echo "BUILDER COPY COMPLETE"

EXPOSE 8080
RUN chmod +x app.jar
