version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: java -jar -Dspring.profiles.active=prod app.jar
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8080
    ports:
      - 8080:8080

volumes:
  static:
  media: